name: .NET

on:
  push:
    branches: [ main, release/* ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    
    - name: Checkout    
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
#    - name: Restore dependencies
#      run: dotnet restore
      
#    - name: Build
#      run: dotnet build --no-restore /p:Version=${{ steps.gitversion.outputs.nuGetVersion }}
      
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
      
    - name: Nuget Pack
      run: dotnet pack -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersion }} --output nupkgs --configuration Release
      
    - name: Nuget Push
      run: dotnet nuget push "/nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
            
#    - name: Publish NuGet
#      uses: brandedoutcast/publish-nuget@v2.5.5
#      with:
#        VERSION_STATIC: ${{ steps.gitversion.outputs.nuGetVersion }}
#        TAG_COMMIT: false
#        # Filepath of the project to be packaged, relative to root of repository
#        PROJECT_FILE_PATH: Flexerant.Math.csproj
#        # API key to authenticate with NuGet server
#        NUGET_KEY: '${{ secrets.NUGET_API_KEY }}'

