name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Fetch tags for GitVersion
      run: git fetch --tags

    - name: Fetch master for GitVersion
      if: github.ref != 'refs/heads/master'
      run: git branch --create-reflog master origin/master

    - name: GitVersion
      id: gitversion  # step id used as reference for output values
      uses: roryprimrose/rungitversion@v1.0.0
  
    - name: Output version values 
      run: |
        echo "NuGetVersion: ${{ steps.gitversion.outputs.NuGetVersion }}"
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:AssemblyVersion=${{ steps.gitversion.outputs.NuGetVersion }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish NuGet
      # You may pin to the exact commit or the version.
      # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Flexerant.Math.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: '${{ secrets.NUGET_API_KEY }}'
  
