name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitVersion
      id: gitversion
      uses: nmcc/actions/gitversion@v1
      with:
        path-to-gitversion: packages/GitVersion.CommandLine/tools/GitVersion.exe
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:AssemblyVersion=${{ steps.gitversion.outputs.SemVer }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish NuGet
      # You may pin to the exact commit or the version.
      # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: Flexerant.Math.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: '${{ secrets.NUGET_API_KEY }}'
  
